### ISSUE TITLE
Design a logo for Rollcall

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#1]
**Design a logo for Rollcall** 

Implement logo designs in different formats 
* SVG
* PNG
* JPG
`Create favicons` 

**Implementation**

Create designs and share screenshots in comment section
Create a folder named Resource and upload logo design .

**Procedure**

Claim this issue: Comment below that you want to work on this issue
Write relevant commit message
Create a PR

**Comment by Nishant-Shukla** [comment]
I would like to work  on this issue @Swarnimashukla

**Comment by Nishant-Shukla** [comment]
<img width="377" alt="Rollcall" src="https://user-images.githubusercontent.com/72122864/94777695-83e0ba00-03e1-11eb-8998-35e802cb1c0b.PNG">

Here is my solution

**Comment by anshulhub** [comment]
![Capture](https://user-images.githubusercontent.com/67779730/95315829-a3c82000-08b0-11eb-8b51-72bacc48c0f7.JPG)
How about this.?

**Comment by ananthalakshmiragi** [comment]
hi, if this is still open, can I still submit a design?

**Comment by Swarnimashukla** [comment]
Sure, @ananthalakshmiragi  go for it

**Comment by ananthalakshmiragi** [comment]
![AAMS](https://user-images.githubusercontent.com/17941997/95660307-988d2280-0b44-11eb-8e10-da95f4723bf2.jpg)


Added this. Also created a PR.

**Comment by rishitbhojak** [comment]
Hey, if it is still open, I would like to contribute. Please assign this issue to me

**Comment by vermatanu** [comment]
I would like to work on this. please assign it to me!

**Comment by ChitvanRamani22** [comment]
I would like to work on this. please assign it to me!

**Comment by IdealisticINTJ** [comment]
I would like to contribute. Please assign this issue to me.

**Comment by mehak2323** [comment]
Hi, I want to work on it, can you please assign this issue to me?

**Comment by Sapna2001** [comment]
@Swarnimashukla is this issue open for all?

**Comment by chehak123** [comment]
Hi, I want to work on it as a participant in GSSOC'21, can you please assign this issue to me?

**Comment by Nidhideveloper** [comment]
I would like to contribute for it as a participant of GSSOC'21

**Comment by abhishree07** [comment]
I would like to contribute to this issue @Swarnimashukla

**Comment by RiaKokate** [comment]
Hey @Swarnimashukla 
I hope you are fine and doing well.
I have previous experience with logo design and would like to get assigned for this work under GSSOC'21. Can you please assign the following to me?

**Comment by RiaKokate** [comment]
Thanks mam for assigning the task to me.

**Comment by shubhnanda** [comment]
hey @Swarnimashukla 
I would  like to contribute to the issue .
Please do assign me this task

**Comment by sherin527** [comment]
Hi, I would also want to contribute to this issue, could you assign me also this task.

**Comment by Sapna2001** [comment]
![ROLLCALL](https://user-images.githubusercontent.com/56690856/110365778-748a2a80-806b-11eb-9fd0-2e39d6a98c7b.png)

Added this to the resources folder and have made a PR also.

**Comment by Ayushisood** [comment]
Hii@Swarnimashukla 
I would like to degin a logo for RollColl
and contribute to this task..

**Comment by anushree71199** [comment]
I would like to design a logo for your issue under Gssoc '21, can you assign this issue to me?

**Comment by deeptea22** [comment]
Hi ! Could you please assign this to me as part of GSSOC'21. Have already started working on it!

**Comment by RiaKokate** [comment]
Mam, I'm a first year student and a bit confused about the submission of
tasks for GSSOC'21.
As one of my task is logo design for your project,I'm ready with my logo
designs and wanting to upload the following. Can you guide me for this?

**Comment by abhishree07** [comment]
![Rollcall](https://user-images.githubusercontent.com/68280108/110516790-0ce9e300-8130-11eb-9e78-d89d9023a7f9.png)
Thank you for assigning this task to me. I have attached my logo's screenshot and have also sent a PR.

**Comment by siddharth-143** [comment]
Hi, I want to work on it, can you please assign this issue to me?

**Comment by vermatanu** [comment]
@RiaKokate you need to fork this repository, then add the logo image in the resource file(in the forked repo). after than when you go to the master(original) repository, you might encounter the option of compare changes and create pull request. you have to create a pull request mentioning what you have added/what changes you have made. 
take a look at this: https://try.github.io/
hope you find this useful :)

**Comment by janvi01** [comment]
I want to work on this issue, can it be assign to me?

**Comment by Astha-glitch** [comment]
I would like to work on this issue as a participant of Gssoc 21

**Comment by RiaKokate** [comment]
Thanks you So much

**Comment by Swarnimashukla** [comment]
Hi all,  Please go through [Discussions](https://github.com/Swarnimashukla/Automatic-attendance-management-system/discussions/33)  , it will clear your doubts regarding issues and how you can work on it. 

You can definitely introduce yourself there and let me know what made you interested in this project 🤩

I would like to mention  **anyone can contribute to issues labeled " Open_for _all"  without being assigned to it**, we will be merging pr of all designs who pass a certain design criteria in terms of aesthetics, typography and presentation. 

✨✨ But you need not to wait for anything to show your creativity. ✨✨

@vermatanu  thank you for taking up question from @RiaKokate , hope doubts are clear and I request you to discuss all these queries under Discussions section

**Comment by ShrutiKhatri826** [comment]
Hi @Swarnimashukla 
I am a GSSOC'21 participant. I would like to take up this issue. Can you please assign it to me? Hope to hear soon from you!

**Comment by DarthSalad** [comment]
I would like to work on this issue.

**Comment by pallavidhere23** [comment]
I am interested to work on this issue can u please assign me this under GSSOC'2021

**Comment by Rayman-Sodhi** [comment]
Hi I would also like to work on this issue under GSSOC'21

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by AasthaRS** [comment]
@Swarnimashukla I want to work on this issue. Will try my best to give you a simple yet meaningful logo. Please assign this issue to me.

**Comment by Pallavi-02** [comment]
I'm the Participant of GSSOC'21. Please assign me this issue.I would like to contribute to this project

**Comment by Swarnimashukla** [comment]
Hi all, we plan to close this issue by 15th March, Monday EOD . Those who intend to make a pr for this issue can do so by deadline.  Will share feedbacks and improvements for those who created PR's soon .

**Comment by ainy-123** [comment]
i'm a participant of GSSOC'21.I would like to contribute to this issue,Please assign it to me @Swarnimashukla .

**Comment by kanishkaa24** [comment]
Hello Mam. Can I work on this issue as a GSSOC participant?

**Comment by rajeshpanjiyar** [comment]
I am a participant in GSSoC'21 and I want to work on this. As it is mentioned with open for all tag so I will be generating pull request as I complete.

**Comment by rajeshpanjiyar** [comment]
Here is the logo I am able to design. For more transformation please do inform me.
![image](https://user-images.githubusercontent.com/78999467/111065318-2482ec00-84e1-11eb-8f4c-c32134e8fb91.png)

**Comment by garvitraj** [comment]
@Swarnimashukla as per ur suggestion on the last one i tried to have 2 to 3 variation i m uploading the file below pls suggest any further change
Thanks
![Roll Call](https://user-images.githubusercontent.com/62978449/111078603-52d1ed00-851c-11eb-94b1-51a2e6b7de40.png)
![Roll Call (1)](https://user-images.githubusercontent.com/62978449/111078606-549bb080-851c-11eb-9f89-a2ea72f7504b.png)
![Roll Call (2)](https://user-images.githubusercontent.com/62978449/111078608-55ccdd80-851c-11eb-9df6-ea6533e5c8b1.png)

**Comment by harshita2319** [comment]
![IMG_20210315_004356](https://user-images.githubusercontent.com/60272753/111081277-86b30f80-8528-11eb-8e15-e4c0531c1a75.jpg)
![rollcall (2)](https://user-images.githubusercontent.com/60272753/111081280-89ae0000-8528-11eb-81ff-9844d41bdaae.png)
Have attached two files.

**Comment by AnkushSinghGandhi** [comment]
![ROLLCALL](https://user-images.githubusercontent.com/55637484/111082790-1c05d200-8530-11eb-8f1e-ae9e4687077b.png)
I just made a logo for rollcall also created the pr #85

**Comment by Swarnimashukla** [comment]
@garvitraj  it looks nice 👍 share all three images with proper naming as pr  

For all, 
Please ensure that pr's made are not directly for master branch rather a separate branch and designs, logos need to be added within a specific folder, participant can name the design file as  

Example : "Logo_Design _Participantname" 
                 "Landing_Page_Wireframe_Participantname"

Try to go through following git tutorial
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
It will help you to rewrite history by rebasing and squashing commits

**Comment by Swarnimashukla** [comment]
> ![IMG_20210315_004356](https://user-images.githubusercontent.com/60272753/111081277-86b30f80-8528-11eb-8e15-e4c0531c1a75.jpg)
> ![rollcall (2)](https://user-images.githubusercontent.com/60272753/111081280-89ae0000-8528-11eb-81ff-9844d41bdaae.png)
> 
> Hey, I'm a GSSoC'21 participant. I've just attached the files here without creating a pr as advised on the project channel.

Please make the pr

**Comment by harshita2319** [comment]
> > ![IMG_20210315_004356](https://user-images.githubusercontent.com/60272753/111081277-86b30f80-8528-11eb-8e15-e4c0531c1a75.jpg)
> > ![rollcall (2)](https://user-images.githubusercontent.com/60272753/111081280-89ae0000-8528-11eb-81ff-9844d41bdaae.png)
> > Hey, I'm a GSSoC'21 participant. I've just attached the files here without creating a pr as advised on the project channel.
> 
> Please make the pr

Done, pr#90.

**Comment by manasvvi1** [comment]
Hey i want to work on the design. Can you please assign it to me?

**Comment by Avnish5** [comment]
Kindly assign this task to me under GSSOC 2021.

**Comment by Jagannath8** [comment]
I would like to work on this issue @Swarnimashukla . Please assign it to me.

**Comment by Dhriti-Roy** [comment]
Hey @Swarnimashukla , is this issue still open...I would like to work on it. Kindly assign it to me.
