### ISSUE TITLE
Add FAQs section for GSSoC'21

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#108]
As this project is shortlisted to accept contributions under GSSoC, we are supposed to include a dedicated FAQ section for GSSoC in README.md after Contribution Guidelines

Refer to [FAQs section ](https://gssoc.girlscript.tech/FAQs.html)

**Comment by iamansoni** [comment]
I would like to work on this task!
You can assign it to me!
