### ISSUE TITLE
Creating a contact Us and About us button .

### ISSUE THREAD

**Issue by shefali12-ab** [Swarnimashukla/Automatic-attendance-management-system#109]
Hey,
I am one of pariticipant of GSSOC'21, I would like to contribute by creating a contact US and About Us button and About us button will redirect to a page which contains all the information related to this project and how it helps goverment.
looking forward for your reply
Thank you.

**Comment by Swarnimashukla** [comment]
@shefali12-ab  where do you plan to add these buttons exactly ?

**Comment by shefali12-ab** [comment]
I have cloned this repository , I didn't find index.html file in that folder. I want to add that contact Us button on top right corner of page. since the website is not designed yet I think so, you can tell me where to place it .and if some one is working on issue for creating the website i will collobrate with them.
