### ISSUE TITLE
Adding a homepage or an index page that has a navbar and other relevant details 

### ISSUE THREAD

**Issue by ShambhaviSharma0110** [Swarnimashukla/Automatic-attendance-management-system#110]
I would like to add a homepage to this project which has a navbar, footer, and other such elements that might be relevant

**Comment by ANSHIKA1806** [comment]
@Swarnimashukla @suyashgautam @bhubesh757 

Please assign this task to me , I am good in this task , I had done this type of task earlier . I would love to contribute in this project. Homepage is the most important page of a website , it gives all over the idea of the website content. It's help to navigate throughout the website.


![home2](https://user-images.githubusercontent.com/71966377/111903004-121b2c00-8a66-11eb-8f6a-66c299837c58.jpg)
![home3](https://user-images.githubusercontent.com/71966377/111903007-134c5900-8a66-11eb-8228-3810b2d2255f.jpg)
![home1](https://user-images.githubusercontent.com/71966377/111903012-1cd5c100-8a66-11eb-9b7b-d3a01b8dba9e.jpg)
