### ISSUE TITLE
Responsive navbar for RollCall

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#117]
Check for issue #107  and add elements accordingly. 

 In mobile view, navbar should toggle on button click and vary it's size according to screen size in desktop as well as mobile view.

Tech Stack : MERN Stack

**Comment by Priyanshu078** [comment]
May I wark on this issue I am a GSSOC participant

**Comment by pragati-kumar** [comment]
@Swarnimashukla  If this issue needs to be taken up as a priority then please consider assigning it to me. I am a GSSOC'21 participant.

**Comment by shwetaIAF** [comment]
@Swarnimashukla I am a GSSOC participant and I want to work on this issue... can you please assign it to me too?

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by Avnish5** [comment]
@Swarnimashukla Kindly assign this task to me under GSSOC 2021.

**Comment by Swarnimashukla** [comment]
@pragati-kumar  what's the update on this issue?

**Comment by naqeeb2710** [comment]
if anyone is not working on it kindly assign it to me.
i would like to work on this

**Comment by Swarnimashukla** [comment]
@shwetaIAF  what's the update on this task?

**Comment by shwetaIAF** [comment]
You can assign this task to another one!
Actually I am unable to manage time.

**Comment by pragati-kumar** [comment]
> @pragati-kumar what's the update on this issue?

I'm so sorry for the late response ma'am but my whole family has been tested covid positive and thus, I'm unable to contribute currently. My sincere apologies.

**Comment by Swarnimashukla** [comment]
No issues @pragati-kumar, hope your family recovers soon.

**Comment by Swarnimashukla** [comment]
@naqeeb2710  you can work on this task now, and @shwetaIAF  thanks for the clarification

**Comment by Subhangini** [comment]
Can I work on this issue @Swarnimashukla

**Comment by Swarnimashukla** [comment]
@naqeeb2710  what's the update on the task?

**Comment by harshita2319** [comment]
If no one is working on this then I'm in!

**Comment by harshita2319** [comment]
Hey , I can't figure out the folder for code in the github repo. Maybe the code for MERN stack has not been started. So should I create a file myself  since there's no index or app.js file?
Or am I missing out on something?

**Comment by Swarnimashukla** [comment]
Yes you can create a file by youself there is no code as of now for website  @harshita2319
