### ISSUE TITLE
Footer for RollCall

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#118]
Check for issue #107 , wireframes and add elements accordingly.

Tech Stack : MERN Stack

**Comment by Abhishekkr93** [comment]
I would like to contribute as a Gssoc21 participant. could you please assign me this? @Swarnimashukla

**Comment by Swarnimashukla** [comment]
@Abhishekkr93  what's the update regarding this task?

**Comment by Abhishekkr93** [comment]
@Swarnimashukla yes mam , I'm working on it but there is 
my midsemm exam , so therefore delay in making pr. Can you please give me 2 days , I'll fix this.

**Comment by Abhishekkr93** [comment]
@Swarnimashukla hello mam, I am unable to find the codebase of the rollcall website, after that, I will fork, clone, add the code of the footer section.
please guide me!  thank you.

**Comment by Swarnimashukla** [comment]
@Abhishekkr93  hey I have created a separate branch " Website" since there is no code for rollcall website as of now that's why you can't find any codebase , you may create your pr in "Website" branch keeping file name as "Rollcall_footer"

**Comment by Abhishekkr93** [comment]
Okay Ma'am. Thanks for update. I'll do that. @Swarnimashukla

**Comment by Abhishekkr93** [comment]
@Swarnimashukla  ma'am,  
I have some queries;

Can you please provide me all the social media profile links, I have to add in the footer section! The T&C page is not ready yet, so I left them the blank link, after this page is ready, I will add the link to the T&C page.

**Comment by Swarnimashukla** [comment]
For now keep everything blank only just include the icons in footer section for all social media links

**Comment by Abhishekkr93** [comment]
okay, mam, everything is done as per your requirement. here is a screenshot. can I make PR now? @Swarnimashukla 
![signal-2021-04-06-183043](https://user-images.githubusercontent.com/56020385/113714691-49e0cf80-9706-11eb-9b51-e6952158fd76.jpeg)

**Comment by Swarnimashukla** [comment]
Ya please go for pr , just make sure you create pr in website branch and name it "RollCall_footer"  with single commit  @Abhishekkr93

**Comment by Abhishekkr93** [comment]
Okay mam!👍

**Comment by Abhishekkr93** [comment]
@Swarnimashukla done mam, have made PR #149 RollCall_footer. Kindly review and merge it.

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by Avnish5** [comment]
@Swarnimashukla Kindly assign this task to me under GSSOC 2021.

**Comment by Abhishekkr93** [comment]
@Swarnimashukla  done mam, have made PR #155 Added Footer for Rollcall Website. Kindly review and merge it.
