### ISSUE TITLE
UI Design for Landing Page

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#119]
Create a final UI Design including elements present in wireframes(check resource branch to find wireframe designs) use color palette from #107  and font style

**Comment by shristi99** [comment]
Please assign this issue to mee as I am the GSSOC'21 participant

**Comment by shwetaIAF** [comment]
Please assign this issue to me also as I have good experience in UI designs and want to contribute as a GSSOC'21 participant.

**Comment by bhubesh757** [comment]
> Please assign this issue to me also as I have good experience in UI designs and want to contribute as a GSSOC'21 participant.

@shwetaIAF Its Already Assigned , so i can do one favour , you both can work on this issue , i will ask to the mentor and i will remind you!

**Comment by shwetaIAF** [comment]
Okay!
Thanks a lot.

**Comment by shristi99** [comment]
Hello @Swarnimashukla  
I am working on UI Design please give me some more time and tell me what features I have to add to the landing page.

**Comment by shristi99** [comment]
Here comes the UI design of the landing page 
https://www.figma.com/file/uHZ6lSaik7dON973Hr6kHL/Rollcall-landing-page?node-id=0%3A1
Please let me know the required changes.
Thank You

**Comment by shristi99** [comment]
Here comes the UI design of the landing page
https://www.figma.com/file/uHZ6lSaik7dON973Hr6kHL/Rollcall-landing-page?node-id=0%3A1
Please let me know the required changes.
Thank You

**Comment by garvitraj** [comment]
@Swarnimashukla i would like to work on this issue please assign this issue to me 
will be completing the design in 2 days

**Comment by Swarnimashukla** [comment]
@shristi99  this looks nice 👍  please go ahead with pr

**Comment by Swarnimashukla** [comment]
> @Swarnimashukla i would like to work on this issue please assign this issue to me
> will be completing the design in 2 days

hey for now this issue is completed  we can work on improvements later on

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by Avnish5** [comment]
@Swarnimashukla Kindly assign this task to me under GSSOC 2021.
