### ISSUE TITLE
UI design for features page

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#121]
Create a final UI Design including elements present in wireframes(check resource branch to find wireframe designs) use color palette from #107 and font style

**Comment by deeptea22** [comment]
@Swarnimashukla Hey! I would like to work on this issue. Please assign this to me as a part of GSSoC'21. Thanks :)

**Comment by deeptea22** [comment]
@Swarnimashukla This is what i have come up with so far. Please let me know the required changes. Thank you :)
https://www.figma.com/file/HeGwdICyeIfZEarbu4tM5I/Roll-Call?node-id=0%3A1

**Comment by Swarnimashukla** [comment]
hey @deeptea22   I think both screens should be a single screen right? page hierarchy needs to be :

1. Features
2. Hardware
3. Software
4. USP

also please add details within these sections because we are creating UI so detailing matters a lot here , we are supposed to write everything all the sub-content that needs to be coded (including sentences, headings, subheadings)

**Comment by deeptea22** [comment]
Okay! I will make theses changes and send you the updated one. Thank you.

**Comment by deeptea22** [comment]
Hey, I have made all the requested changes. Please have a look 
1. at the design here : https://www.figma.com/file/HeGwdICyeIfZEarbu4tM5I/Roll-Call?node-id=0%3A1
2. at the prototype here : https://www.figma.com/proto/HeGwdICyeIfZEarbu4tM5I/Roll-Call?node-id=1%3A2&scaling=contain&page-id=0%3A1

Thank you :)

**Comment by Swarnimashukla** [comment]
@deeptea22  this looks nice to me , please go for pr, just create it in resource branch with name " FeaturePage_UI_yourname" and make sure there is a single commit only

**Comment by deeptea22** [comment]
@Swarnimashukla I have created the PR #131. Please review it. Thank you :)
