### ISSUE TITLE
Face and Eye Detection

### ISSUE THREAD

**Issue by anubhav201241** [Swarnimashukla/Automatic-attendance-management-system#123]
Hi, my name is Anubhav and I'm a Gssoc'21 Participant and I want to contribute Face and Eye Detection using an open cv in 
Face-Database folder, I want to add my code to it 

@Swarnimashukla please assign this task to me :)

**Comment by anubhav201241** [comment]
This is not a bug, I only want to add the face and eye detection file and readme file in the Face-database Folder as it is empty so that's why I'm asking.

**Comment by anubhav201241** [comment]
Thank you mam for assigning me this :)

**Comment by Swarnimashukla** [comment]
@anubhav201241  do create a pr in separate branch once you are done

**Comment by anubhav201241** [comment]
> @anubhav201241 do create a pr in a separate branch once you are done

Ok mam, Thank you mam :)

**Comment by YMMSSH** [comment]
hi ,  I'm a Gssoc'21 Participant and I want to participate in this issue what should I do ?

**Comment by YMMSSH** [comment]
@Swarnimashukla 

> hi , I'm a Gssoc'21 Participant and I want to participate in this issue what should I do ?

@Swarnimashukla

**Comment by anubhav201241** [comment]
@Swarnimashukla  Please check this and merge it Face_EyeDetection #130
Thank you :)

**Comment by anubhav201241** [comment]
Thank you mam for merging my PR :))
