### ISSUE TITLE
Create mysql database 

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#14]
**Task**

Create a database with following columns 

1. ID(Rollno.)
2. Name
3. Complete Rollno.
4. Person ID(Azure tag)
5. Mobile number(valid datatype - numerical)

Upload .db file

**Procedure**

Comment below that you would like to work on this issue
Write clean code
Make a pr in separate branch

Happy Coding

**Comment by Nishant-Shukla** [comment]
I would like to work on this issue @Swarnimashukla
