### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by sarasij190** [Swarnimashukla/Automatic-attendance-management-system#147]
I want to add new features on it in which

1. the admin can calculate the total working hours or active hours of the employee which will show the total active hours and,
2. improve the UI of the system
Can I work on this??

**Comment by sarasij190** [comment]
Actually I want to add a feature call admin in which view employees working or active hours. It will be be extra feature to this project
I am currently working on the code .
I can proceed if you accept..can you proceed??

**Comment by sarasij190** [comment]
Can I procced??

**Comment by Swarnimashukla** [comment]
@sarasij190  could you explain a bit how is this related to rollcall ?
