### ISSUE TITLE
Add contributors at the bottom of readme file

### ISSUE THREAD

**Issue by srisatya1197** [Swarnimashukla/Automatic-attendance-management-system#148]
I want to add contributors at the bottom of the file so that it look like this
ADD:
![sc](https://user-images.githubusercontent.com/78905067/113710268-1f404800-9701-11eb-8987-7499c0283fa5.png)

I want to work on this issue as GSSOC 21 participant @muthuannamalai12 @Swarnimashukla .

**Comment by suyashgautam** [comment]
Hey @srisatya1197 sure you can work on it.

**Comment by srisatya1197** [comment]
@suyashgautam Ok.
