### ISSUE TITLE
I want to add no.of forks,issues,stars and other in readme file.

### ISSUE THREAD

**Issue by srisatya1197** [Swarnimashukla/Automatic-attendance-management-system#163]
I want to add no.of forks , issues, stars in readme file .
Example:
![ss5](https://user-images.githubusercontent.com/78905067/115118932-724cb180-9fc3-11eb-98aa-de7a97582473.png)
I want to work on this . Please assign me this issue @muthuannamalai12 @Swarnimashukla .

**Comment by Srishti013** [comment]
Can I be assigned for the issue if its not yet done @Swarnimashukla

**Comment by srisatya1197** [comment]
@Srishti013 Hello thanks for your interest the pr is ready.
