### ISSUE TITLE
Create use case diagram for project 

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#19]
Task

Make a clear use case diagram representing all important parts of project

Comment below that you would like to work on this issue
Write clean code
Make a pr in separate branch

Happy Coding

**Comment by Nishant-Shukla** [comment]
Can you brief me about main components about idea ? @Swarnimashukla

**Comment by Swarnimashukla** [comment]
@Nishant-Shukla  sure ,

Major components include students , teacher, government officials , database , enrolment, updation of records
