### ISSUE TITLE
Design Landing page for website

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#2]
Task 

Design a detailed  high fidelity landing page for website , add all necessary features for a product website .
References : [Link1](https://attendlab.com/) | [Link2](https://attendace-system2020.000webhostapp.com/)

**Implementation**

Create designs and share screenshots in comment section
Add your design in resource folder

**Procedure**

Claim this issue: Comment below that you want to work on this issue
Write relevant commit message
Create a PR

**Comment by Avnish5** [comment]
Kindly give this task to me.
I can create the landing page for website....

**Comment by achalesh27022003** [comment]
I want  to work on it. Pls assign me this issue under GSSoC

**Comment by Avnish5** [comment]
Thanks for assigning me this task to me.This is going to be my first contribution in open source

**Comment by Ayushisood** [comment]
Hii @Swarnimashukla 
I would like to design a landing page for this website 
Kindly assign the task to me
I am selected as GSSOC'21 participant

**Comment by mohdjameel2412** [comment]
please assign it to me under gssoc21

**Comment by Avnish5** [comment]
@Swarnimashukla i had make the landing page.Kindly tell me about what product  or product feature you want add in the landing page.

Kindly give some info about product..

**Comment by midhun-b-m** [comment]
Hello @Swarnimashukla, 
I would like to work on the landing page design. 
I am a participant of GSSoC'21.

**Comment by SpecTEviL** [comment]
Hey, @Swarnimashukla Vishal Patil here, I would love to contribute to this issue along with @Avnish5 under GSSoC'21. As this is a level 2 issue two people can finish this fast. You can view my previous work from https://spectevil.github.io and decide.
Thanks!

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by Pallavi-02** [comment]
Hey...i'm GSSOC'21 participant. Please assign me this issue.I would love to contribute in this project

**Comment by Swarnimashukla** [comment]
![screencapture-file-C-Users-swarn-Desktop-Not-so-important-RollCall-master-1-RollCall-master-RollCall-html-2021-03-13-22_48_41](https://user-images.githubusercontent.com/30214391/111038376-8d6d5400-844e-11eb-817a-3da5a8056673.png)


@Avnish5  you can refer this we are looking for something in these lines

**Comment by kanishkaa24** [comment]
Hello Mam. Can I work on this issue as a GSSOC participant?

**Comment by garvitraj** [comment]
@Swarnimashukla pls assign this issue to me. will try to make a beautiful landing page

**Comment by Swarnimashukla** [comment]
@SpecTEviL  you can make a separate pr as well once done , @Avnish5  could you please share your work so we could see the progress

**Comment by garvitraj** [comment]
@Swarnimashukla can i start with the issue of designing the landing page? Will give best asap

**Comment by Avnish5** [comment]
> @SpecTEviL you can make a separate pr as well once done , @Avnish5 could you please share your work so we could see the progress

Mam tomorrow i will make the pr and finish this work finally by tomorrow.

**Comment by SpecTEviL** [comment]
> @SpecTEviL you can make a separate pr as well once done , @Avnish5 could you please share your work so we could see the progress

Sure will do that @Swarnimashukla!

**Comment by Avnish5** [comment]
@Swarnimashukla Mam i have make the PR request for the landing page.
Kindly check and merge it.

**Comment by SpecTEviL** [comment]
Hey, @Swarnimashukla just wanted to let you know to please wait for me also to showcase my work as I've started work on this issue. Please don't close this issue, just give me one day i.e. tomorrow I'll update you regarding my design. 
Thanks!

**Comment by Swarnimashukla** [comment]
@SpecTEviL  sure you can take your time just inform us with your progress

**Comment by Swarnimashukla** [comment]
![Header+top page](https://user-images.githubusercontent.com/30214391/111192865-8e81bb00-85df-11eb-9b9d-555f378c31fd.png)

I would like to see designs of this quality at least you don't need to use image,  color anything just show what info needs to be presented where , that's what we mean by a wireframe

**Comment by saswatsam786** [comment]
Mam, I would like to works on this issue. Please assign me this.
I will try to submit this in a minimum of 10 days

**Comment by SpecTEviL** [comment]
> @SpecTEviL sure you can take your time just inform us with your progress

Yes @Swarnimashukla, the work is 80% done. Just some final touches are to be made. I'll update you with the first version of my design by 4 pm today. Also as it was urgent so I haven't made any wireframe for the design.
Thanks!

**Comment by garvitraj** [comment]
@Swarnimashukla please assign this issue to me so that I can start with the wireframe, get it reviewed, and then proceed further with the design.
Thans

**Comment by SpecTEviL** [comment]
Hey, @Swarnimashukla I tried this. You can give your feedback and any suggestions are most welcomed. I'm still trying to add some vector arts which will enhance the UI. For now, this is the first version.
Thank You!

1. When the sidebar is open:
![Rollcall Landing page 1](https://user-images.githubusercontent.com/62737267/111296334-5d9e9600-8672-11eb-9fa2-71e123509a47.png)

2. When the sidebar is closed:
![Rollcall Landing Page 2](https://user-images.githubusercontent.com/62737267/111296379-6c854880-8672-11eb-9590-bf082ec564b2.png)

**Comment by Swarnimashukla** [comment]
@SpecTEviL  this looks fine, can we separate testimonials and signup form because testimonials should be visible properly and keep it simple only no need of vector art as of now, we still need to decide on color palette of website that's why we needed wireframes only so focus on making User experience better, how quickly user could find relevant information

**Comment by SpecTEviL** [comment]
> @SpecTEviL this looks fine, can we separate testimonials and signup form because testimonials should be visible properly and keep it simple only no need of vector art as of now, we still need to decide on color palette of website that's why we needed wireframes only so focus on making User experience better, how quickly user could find relevant information

Ya sure will work on this @Swarnimashukla!
Thank you for your feedback!

**Comment by Avnish5** [comment]
![SaaS Landing Page Wireframe - SaaS Landing Page Wireframe · Moqups - Google Chrome 18-03-2021 11_49_21 (2)](https://user-images.githubusercontent.com/68527921/111582252-952b5080-87e0-11eb-8c41-633849ac1bdc.png)
![SaaS Landing Page Wireframe - SaaS Landing Page Wireframe · Moqups - Google Chrome 18-03-2021 11_49_41 (2)](https://user-images.githubusercontent.com/68527921/111582255-965c7d80-87e0-11eb-98f0-bc7daa6df6a1.png)
![SaaS Landing Page Wireframe - SaaS Landing Page Wireframe · Moqups - Google Chrome 18-03-2021 11_49_48 (2)](https://user-images.githubusercontent.com/68527921/111582261-96f51400-87e0-11eb-81c0-7704135ece85.png)
![SaaS Landing Page Wireframe - SaaS Landing Page Wireframe · Moqups - Google Chrome 18-03-2021 11_49_52 (2)](https://user-images.githubusercontent.com/68527921/111582267-98bed780-87e0-11eb-9d00-0f006ef00098.png)
![SaaS Landing Page Wireframe - SaaS Landing Page Wireframe · Moqups - Google Chrome 18-03-2021 11_50_10 (2)](https://user-images.githubusercontent.com/68527921/111582274-99f00480-87e0-11eb-9972-fd710b58f4ae.png)


@Swarnimashukla Kindly look at this wireframe.
Kindly give me the feedback also

**Comment by Swarnimashukla** [comment]
@Avnish5  this looks nice , I am not sure if we need pricing as of now but we can keep it. You can go for pr, just make sure you follow all guidelines as given on discord channel (rollcall)

**Comment by Avnish5** [comment]
@Swarnimashukla  okk mam thanku i will make pr now.

**Comment by Avnish5** [comment]
@Swarnimashukla Mam i have created the Pull request.
Kindly check and merge it....

**Comment by Swarnimashukla** [comment]
> @Swarnimashukla Mam i have created the Pull request.
> Kindly check and merge it....

@Avnish5  can you recheck , i can't find your pr

**Comment by Avnish5** [comment]
@Swarnimashukla Sorry mam there was some technical issue.

Kindly now check it.

**Comment by Avnish5** [comment]
anybody can please tell me how to squash the commits.

**Comment by kanishkaa24** [comment]
> anybody can please tell me how to squash the commits.
git rebase HEAD~(number of commits)
git add .
git commit ....

**Comment by Avnish5** [comment]
@Swarnimashukla  Kindly check and merge it mam

**Comment by Avnish5** [comment]
@kanishkaa24 Again very special thanks to you for your help....

**Comment by Avnish5** [comment]
@Swarnimashukla Thanks for your guidance and support mam.
This is my first  contribution in open source.
And i really liked the way the open source source community work.

Again Thanku very much...

**Comment by SpecTEviL** [comment]
Great Job @Avnish5. Keep up the good work ;-)

**Comment by Avnish5** [comment]
> Great Job @Avnish5. Keep up the good work ;-)

Thanks brother...

**Comment by Swarnimashukla** [comment]
@SpecTEviL  are you creating a pr for this issue?

**Comment by SpecTEviL** [comment]
> @SpecTEviL are you creating a pr for this issue?

Not really @Swarnimashukla  I've stopped working on it as I thought that you guys have finalized @Avnish5's design and I personally also liked it that's why.
If needed I can work on it. Do let me know about this.

Thanks!

**Comment by Swarnimashukla** [comment]
Alright then we are closing this issue
