### ISSUE TITLE
Fix Bug in greetings.yml file

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#23]
**Task**

Improve greetings.yml file with proper syntax

**Procedure**
Comment below if interested in this issue
Once assigned start working 
Write proper commit message in PR

**Comment by nish-d** [comment]
Hi Can I take this up please?

**Comment by Swarnimashukla** [comment]
Yes @nish-d  go for it 👍

**Comment by nish-d** [comment]
@Swarnimashukla Can you please review my PR. Happy to accomodate any more suggestions/ changes.
