### ISSUE TITLE
Create a Information architecture for website

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#28]
*Is your feature request related to a problem? Please describe*
We need information architecture to have a clarity about website and features it provide , IA is basically a user flow chart for website

*Describe the solution you'd like*
Make a flowchart/ IA for website
Look for product based websites to have clarity and idea about all features we could include to represent a product and design flowchart

[Schoolpixa](http://schoolpixa.com/)

[Schoolsmart](https://schoolsmart.in/)

*Additional context*
Include all features and use proper symbols to shows different sections of website

**Comment by vermatanu** [comment]
I can work on this please assign this to me :)

**Comment by mehak2323** [comment]
I would like to work on it, please assign the issue to me. Thanks!

**Comment by Nidhideveloper** [comment]
I would like to contribute as a participant of GSSOC'21

**Comment by manishaag7** [comment]
I would like to work on it, can u assign to me?

**Comment by anushree71199** [comment]
Can I make a contribution to this issue under GSSoc '21?

**Comment by mohdjameel2412** [comment]
please assign it to me under gssoc21

**Comment by Asmita-si** [comment]
I want to work on this issue. Can you please assign it to me?

**Comment by sejalvasan** [comment]
I also want to work on this issue. Can i ?

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by Swarnimashukla** [comment]
Hi all since this issue was assigned for a week and no response there so I have assigned it to @anushree71199  

We will re-assign after 3 days  if there is no response, also please share IA in discussion section before making a pr so if there is any change it could be done with minimal efforts

**Comment by mohammedjameel24** [comment]
Please assign it to @mohammedjameel24

Kindly assign this issue to the same because i registered for gssoc thorough that account 
Apologize for confusions

**Comment by Asmita-si** [comment]
@Swarnimashukla  how to contact the mentors through Discord?

**Comment by Avnish5** [comment]
Kindly assign me thus issue under GSSOC 2021

**Comment by bhubesh757** [comment]
@Asmita-si You can Mention need Help in Discord !, So we Can help you on that articular issue

**Comment by Swarnimashukla** [comment]
Just to give you all a little more reference :

we are supposed to create a flowchart which represent how user will move from one screen to another, suppose home page has 4 sections then when user click on any section it will have subsections, you can refer to links i mentioned on issue description to create one generic IA, since we have few submissions for wireframe of different page so you can check that as well. sharing an example here 

<img width="563" alt="online shoe store" src="https://user-images.githubusercontent.com/30214391/111768831-6f7c7500-88ce-11eb-9f3a-70869c15ad42.PNG">

As per tool you can use https://whimsical.com/ this or anything convenient to you
