### ISSUE TITLE
Create a project admin and mentor section in readme file

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#29]
*Is your feature request related to a problem? Please describe.*
A section in the readme for project admin and mentors to recognize their hard work to grow this project.
there will be a photo (can get from GitHub) and ink their GitHub profile.

**Comment by IdealisticINTJ** [comment]
I would like to work on this. Please assign it to me. :)

**Comment by soumyavemuri** [comment]
Hello, I'd like to work on this under GSSOC. Please assign me to this task.

**Comment by chehak123** [comment]
Hi, I want to work on it as a participant in GSSOC'21, can you please assign this issue to me?

**Comment by manishaag7** [comment]
I want to work on this issue as a GSSOC'21 participant.

**Comment by achalesh27022003** [comment]
I want to work on this issue under GSSoC program. Pls assign me this issue.

**Comment by Polokghosh53** [comment]
Can I ask, are the contributors namely the mentor section at present?

**Comment by mohdjameel2412** [comment]
/please assign it to me under gssoc21

**Comment by gritika18** [comment]
I'm a GSSOC particpant and i would love to work on this issue. Could you please assign it to me?

**Comment by pranavvdesai** [comment]
im a GSSOC participant and i would like to work on this.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by achalesh27022003** [comment]
Guys I am working on this issue. Will send a PR in day or two.

**Comment by achalesh27022003** [comment]
#67
