### ISSUE TITLE
Add an open with gitpod button

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#3]
**Task**

If anyone has any issues in cloning/forking and contributing from their local machine, they can open up the code in gitpod.

**Implementation**

Add an open with gitpod badge/button in readme.md file

**Describe alternatives you've considered**

Gitpod eliminates the friction by providing prebuilt, ready-to-code dev environments with a single click.

**Comment by Hridyanshu** [comment]
I want to work on this issue.
