### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by iamansoni** [Swarnimashukla/Automatic-attendance-management-system#31]
requirements.txt must be added for the project, as it will make the development process easier, and it will ensure that whenever installed, users will have all the working dependencies.

**Comment by Aayush-hub** [comment]
@Swarnimashukla Can I work on issue under GSSoC21 label?

**Comment by sudo-nick16** [comment]
I'd like to work on this issue under GSSoC'21. I deployed my first Django web-app today and dealt with the creation of the requirements.txt file in the process. I'd love to put that knowledge into use. Also, I'm a newcomer to open-source, this could be the issue that I work on. Hope to hear from you soon.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.
