### ISSUE TITLE
Add issue templates 

### ISSUE THREAD

**Issue by Akash20x** [Swarnimashukla/Automatic-attendance-management-system#32]
I want to add issue templates for proposal, feature and documentation types so that there is proper way to create a new issue in your repo.

Please assign me this task as a part of GSSoC'21
and add necessary labels.

**Comment by subhangi2731** [comment]
can you please assign this to me?

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.
