### ISSUE TITLE
Create wireframe for features page

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#4]
**Task**
Design a high fidelity mockup for features page including details 

- All features provided by product

- Hardware / software used 

- USP of project 

**Implementation**

Create designs and share screenshots in comment section
Add your design in resource folder

**Procedure**

Claim this issue: Comment below that you want to work on this issue
Write relevant commit message
Create a PR

**Comment by mu593** [comment]
please assign me these issue

**Comment by Avnish5** [comment]
Kindly assign this task to me.
I had very strong understanding about the UI designs..

**Comment by abhish3k-11** [comment]
Can you please assign this task to me under the label of GSSOC'21. I'm a UI/UX designer and have worked on issues like this before.

**Comment by abhish3k-11** [comment]
@Swarnimashukla please give your input on this wireframe of features page. Let me know if you'd like to suggest some changes. If all is good then I'll make a PR after your reply.


![Web 1920 – 1@2x](https://user-images.githubusercontent.com/67673898/110471804-98e51600-8102-11eb-8c42-95b6403cc05b.png)

**Comment by abhish3k-11** [comment]
@Swarnimashukla Can you guide as  to why PR test failed?

**Comment by Swarnimashukla** [comment]
@abhish3k-11  can we refine the wireframe a little , you need not to worry about the color, try creating a basic wireframes, you can even use Balsamiq tool for that or whatever tool is convenient to you. I would want you to work on minor details like what all elements will be there in navbar? what's present in the footer section and similarly for body , in features page we want to show hardware, software used and details about its functionality that can be found from README.md section

**Comment by kanishkaa24** [comment]
Hello Mam. Can I work on this issue as a GSSOC participant?

**Comment by Swarnimashukla** [comment]
We ( @bhubesh757 @SKAUL05 @suyashgautam ) will re-assign after 3 days if there is no response try creating a simple design first so we could see the progress, also please share design in discussion section before making a pr so if there is any change it could be done with minimal efforts

**Comment by abhish3k-11** [comment]
@Swarnimashukla okay, I'll do the changes asap. If need arise I'll redesign the wireframe completely. 
@kanishkaa24 can you share your discord tag and id so that we can discuss and do the required changes. It will be a waste of time if we both came up with different designs.

**Comment by akankshaaa-08** [comment]
@Swarnimashukla Can I have this issue assigned to me?

**Comment by kanishkaa24** [comment]
![ROLLCALL](https://user-images.githubusercontent.com/71253790/111184297-d6e8ab00-85d6-11eb-9924-5d47c3d2af14.png)
@Swarnimashukla Mam I have prepared have the mockup. If you like the design, I can continue on this or change the pattern.

**Comment by Swarnimashukla** [comment]
![s2](https://user-images.githubusercontent.com/30214391/111192416-069bb100-85df-11eb-8feb-326e1494dedc.PNG)


Alright guys giving you an example this is what a wireframe looks like , very simple no image no color , but just provides enough info on how and where to place a particular element

**Comment by kanishkaa24** [comment]
![Copy of ROLLCALL (1)](https://user-images.githubusercontent.com/71253790/111197055-0356f400-85e4-11eb-9c40-7369a6b4b634.png)
![Copy of ROLLCALL](https://user-images.githubusercontent.com/71253790/111197049-018d3080-85e4-11eb-8d92-3ef28ced6714.png)

**Comment by Swarnimashukla** [comment]
@kanishkaa24  go for a pr, make sure you follow all the guidelines, (can be found on discord channel rollcall)

**Comment by abhish3k-11** [comment]
@Swarnimashukla  can you check this one out please. It fulfills every criteria mentioned.
![Web 1920 – 1](https://user-images.githubusercontent.com/67673898/111583396-59918600-87e2-11eb-9194-63f21dc464d2.png)

**Comment by Swarnimashukla** [comment]
@abhish3k-11  go for pr 👍
