### ISSUE TITLE
add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by kcoder63** [Swarnimashukla/Automatic-attendance-management-system#40]
add code of conduct to maintain the contribution guidelines

**Comment by Tushar1337** [comment]
added it :)

**Comment by i-aayush711** [comment]
Hello!
Can you have multiple assignees for this? I would like to contribute to this.

**Comment by sudo-nick16** [comment]
Hi, I'd like to contribute to this under GSSoC'21. Can you please assign it to me. I'm new to open-source and can't wait to make my first PR. Hope to hear from you soon.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by amritakesh** [comment]
hello
i'm taking part in gssoc 2021. And i would like work on this issue, will you please assign this to me?

**Comment by Upasana1216** [comment]
I would love to contribute to this issue. Please assign this to me

**Comment by madmax-07** [comment]
Hi ,I am a GSSOC participant .I am new to open source and I interested to work on this project

**Comment by simarjeet30** [comment]
Hello!
Can you have multiple assignees for this? 
I would love to contribute to this issue. Please assign this to me

**Comment by khusheekapoor** [comment]
Hello! I am participant in GSSoC'21. I am really intrigued by this issue and would love to work on it. Would be highly obliged if you could assign this to me. Thanks!
