### ISSUE TITLE
add CONTRIBUTING.md

### ISSUE THREAD

**Issue by kcoder63** [Swarnimashukla/Automatic-attendance-management-system#41]
add contributing.md to give a brief about your project and some details to welcome new contributors

**Comment by khareyash05** [comment]
Hi I would like to work on this issue as a part of GSSOC'21

**Comment by khareyash05** [comment]
May I know the level of the issue under GSSOC'21

**Comment by Tushar1337** [comment]
can you assign this to me so that I can make a pull request?
