### ISSUE TITLE
Create a wireframe for product demo page 

### ISSUE THREAD

**Issue by Swarnimashukla** [Swarnimashukla/Automatic-attendance-management-system#5]
**Task**

Design a high fidelity mockup for product demo page  page including 

- Image of product and functionality images 

- USP of project

For now add video of product presentation later it could be updated with demo video .

**Implementation**

Create designs and share screenshots in comment section
Add your design in resource folder

**Procedure**

Claim this issue: Comment below that you want to work on this issue
Write relevant commit message
Create a PR

**Comment by Avnish5** [comment]
Kindly assign this work to me.

**Comment by maanpatel2492** [comment]
> **Task**
> 
> Design a high fidelity mockup for product demo page page including
> 
> * Image of product and functionality images
> * USP of project
> 
> For now add video of product presentation later it could be updated with demo video .
> 
> **Implementation**
> 
> Create designs and share screenshots in comment section
> Add your design in resource folder
> 
> **Procedure**
> 
> Claim this issue: Comment below that you want to work on this issue
> Write relevant commit message
> Create a PR

I can work on this issue.Assign if possible.

**Comment by RiaKokate** [comment]
Hey @Swarnimashukla 
I would like to take up this query. Could you please assign the following query to me?

**Comment by tanishq-arya** [comment]
I would like to work on this issue as a  GSSOC'21 participant. Please assign me this issue.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by Swarnimashukla** [comment]
We ( @bhubesh757 @SKAUL05 @suyashgautam ) will re-assign after 3 days if there is no response, also please share design in discussion section before making a pr so if there is any change it could be done with minimal efforts

**Comment by Swarnimashukla** [comment]
#2   refer to example given in comment section of this issue

**Comment by garvitraj** [comment]
@Swarnimashukla  please assign this issue to me so that I can start with the wireframe, get it reviewed, and then proceed further with the design.
Thanks

**Comment by maanpatel2492** [comment]
> We ( @bhubesh757 @SKAUL05 @suyashgautam ) will re-assign after 3 days if there is no response, also please share design in discussion section before making a pr so if there is any change it could be done with minimal efforts

I have shares pdf of rough wireframe in the discussion section.

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by Avnish5** [comment]
Kindly assign me this task under GSSOC 2021.

**Comment by Swarnimashukla** [comment]
@srishtij2000  are you still working on this issue?

**Comment by garvitraj** [comment]
@Swarnimashukla pls assign this issue to me

**Comment by Avnish5** [comment]
@Swarnimashukla Kindly assign this task to me under GSSOC 2021.

**Comment by garvitraj** [comment]
@Swarnimashukla pls review the design and suggest what should i improve.
There will be more attractive illustrations in final design
Link for design :- https://www.figma.com/file/X3mDRxqRP5jiRHzELNLL6h/Untitled?node-id=0%3A1

**Comment by Swarnimashukla** [comment]
@garvitraj  this looks good you can go for pr as we are working on coding part of this issue and we can surely improve upon designs later on .

**Comment by garvitraj** [comment]
sure would too like to contribute on the frontend issue can you pls give the issue no so that i may start my contribution there too

**Comment by SKV-programmer** [comment]
@Swarnimashukla Kindly assign me this task.

**Comment by harshita2319** [comment]
Hey, I'm a GSSOC participant. I'd like to work on this issue.
