### ISSUE TITLE
Images should be placed in a single folder

### ISSUE THREAD

**Issue by flyingsonu122** [Swarnimashukla/Automatic-attendance-management-system#53]
All images should be placed in a single folder so that it is easier to work on the project

**Comment by flyingsonu122** [comment]
@Swarnimashukla Assign this to me, so that I can fix it

**Comment by flyingsonu122** [comment]
@Swarnimashukla I need to edit README.md for linking images from the folder

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by flyingsonu122** [comment]
> Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

Already assigned to me and I have also created a PR for the same #60 @Swarnimashukla

**Comment by bhubesh757** [comment]
@flyingsonu122 By This week Admin will Add Your PR , Be calm , You will get your points asap
