### ISSUE TITLE
Resources branch is of no use

### ISSUE THREAD

**Issue by flyingsonu122** [Swarnimashukla/Automatic-attendance-management-system#54]
Delete that resources branch, because there is no use of it as all the codes are also present in the default branch

**Comment by Swarnimashukla** [comment]
Hey @flyingsonu122  we planned to keep all images, posters, logo designs in resources , can you check if we can still do the same ?

**Comment by flyingsonu122** [comment]
> Hey @flyingsonu122 we planned to keep all images, posters, logo designs in resources , can you check if we can still do the same ?

I am talking about the resources **branch** not folder @Swarnimashukla

**Comment by flyingsonu122** [comment]
@Swarnimashukla you first merge #60 after that, we will give instruction to the contributors in the README.md to create PR in the resource branch
