### ISSUE TITLE
Will like to update techstack ( add logo)

### ISSUE THREAD

**Issue by rohank2502** [Swarnimashukla/Automatic-attendance-management-system#57]
I will like to update the techstack setion rather than just writing name we can add their logo this will make our read me more attractive !!

**Comment by garvitraj** [comment]
@Swarnimashukla  and @suyashgautam i can give a logo for our project as i too work as a graphic designer and UI/UX. so it would be great if you assign this task to me as a GSSOC21

**Comment by Swarnimashukla** [comment]
@garvitraj  logo designing for RollCall is a separate issue you can contribute there, its open_for_all

**Comment by garvitraj** [comment]
@Swarnimashukla thanx for it will definitely try to give my best.

**Comment by garvitraj** [comment]
@Swarnimashukla i m sone with the logo should i make a pull request

**Comment by garvitraj** [comment]
I have done with the logo i know i took more time but here its final 
we can play with the colour in the logo as per the theme of our website and app. Logo pdf is attached below pls have a look @Swarnimashukla and @rohank2502 
[Roll Call.pdf](https://github.com/Swarnimashukla/Automatic-attendance-management-system/files/6136671/Roll.Call.pdf)

**Comment by bhubesh757** [comment]
@garvitraj just add this under the issue #1
