### ISSUE TITLE
No proper name of files

### ISSUE THREAD

**Issue by flyingsonu122** [Swarnimashukla/Automatic-attendance-management-system#59]
![image](https://user-images.githubusercontent.com/51280276/110979842-25a20500-838b-11eb-8b26-e8dfeba1a0cc.png)

**issues**

![image](https://user-images.githubusercontent.com/51280276/110979994-5d10b180-838b-11eb-929a-bc0cdb56b2c1.png)

naming conventions should be followed

**Comment by Avnish5** [comment]
@Swarnimashukla Kindly assign this task to me under girlscript soc 2021.
